name: example
description: A Flutter project which demonstrates the `flutter_shogi_board` package.
publish_to: none
version: 0.0.6+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shogi_board:
    path: ../

flutter:
  uses-material-design: true
