name: flutter_shogi_board
description: A shogi board widget for Flutter. This widget can be used to render static game board positions, tsume problems or shogi castles.
version: 0.0.6
homepage: https://github.com/defuncart/flutter_shogi_board
repository: https://github.com/defuncart/flutter_shogi_board
issue_tracker: https://github.com/defuncart/flutter_shogi_board/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  shogi: 0.0.4
  pedantic: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
