name: flutter_shogi_board
description: A shogi board widget for Flutter. This widget can be used to render static game board positions, tsume problems or shogi castles.
version: 0.0.7-nullsafety.0
homepage: https://github.com/defuncart/flutter_shogi_board
repository: https://github.com/defuncart/flutter_shogi_board
issue_tracker: https://github.com/defuncart/flutter_shogi_board/issues
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  shogi:
    git:
      url: https://github.com/defuncart/shogi
      ref: main
  pedantic: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
