name: flutter_shogi_board
description: A shogi board widget for Flutter. This widget can be used to render static game board positions, tsume problems or shogi castles.
version: 0.0.7
homepage: https://github.com/defuncart/flutter_shogi_board
repository: https://github.com/defuncart/flutter_shogi_board
issue_tracker: https://github.com/defuncart/flutter_shogi_board/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  shogi: 0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true
